### ISSUE TITLE
Getting error in Swift 3.0

### ISSUE THREAD

**Issue by dis123** [MobileFirst-Platform-Developer-Center/PushNotificationsSwift#1]
In Swift 3.0, I got below error while compiling the code. Below is the function Name:

MFPPush.sharedInstance().registerDevice(nil, completionHandler: {(response: WLResponse!, error: NSError!) -> Void in

Error : Cannot cnvert value of type '(WLResponse!, NSError!)-> Void' to expected argument type '((WLResponse?, NSError?)->Void)!'

Can you please provide quick fix for it? I am stucked at this error.

**Comment by IdanAdar** [comment]
The MobileFirst SDK is not certified for use with Swift 3.0. Please use Swift 2.3.

**Comment by IdanAdar** [comment]
The sample was recently updated for Swift 3.0.
